name: inji-verify SDK NPM Publish

on:
  release:
    types: [ published ]
  pull_request:
    types: [ opened, reopened, synchronize ]

  workflow_dispatch:
    inputs:
      message:
        description: 'Message for manually triggering'
        required: false
        default: 'Triggered for NPM Publish'
        type: string

  push:
    branches:
      - release*
      - master
      - develop*
      - MOSIP*
# 🔐 REQUIRED for npm Trusted Publishing (OIDC)
permissions:
  id-token: write
  contents: read

jobs:
  publish-inji-verify-sdk-to-npm-registry:
    # publish ONLY on manual trigger (as per your original condition)
    if: >
      ${{
        github.event_name == 'workflow_dispatch' &&
        !contains(github.ref, 'master')
      }}
    uses: Prafulrakhade/kattu/.github/workflows/npm-publish-to-npm-registry.yml@MOSIP-44056
    with:
      SERVICE_LOCATION: './inji-verify-sdk'
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
